services:
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    container_name: web_api
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_db
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: web_db
    
volumes:
  db_data: